let hello = 'hello';
let owu = 'owu';
let comString = 'com';
let ua = 'ua';
let oneNumber = 1;
let tenNumber = 10;
let negativeNines = -999;
let oneTwoThree = 123;
let pi = 3.14;
let twoAndSeven = 2.7;
let sixteen = 16;
let trueBool = true;
let falseBool = false;

console.log(hello);
console.log(owu);
console.log(comString);
console.log(ua);
console.log(oneNumber);
console.log(tenNumber);
console.log(negativeNines);
console.log(oneTwoThree);
console.log(pi);
console.log(twoAndSeven);
console.log(sixteen);
console.log(trueBool);
console.log(falseBool);